name = "reservoir_correlation"
authors = ["Zierenberg"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ReservoirComputing = "7c2d2b1e-3dd4-11ea-355a-8f6a8116e294"

[compat]
DrWatson = "2.11.1"
julia = "1.8.0"
